/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void BttnQ_click1(GButton source, GEvent event) { //_CODE_:BttnQ:232846:
  xbee.write('Q');  
  println("BttnQ - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BttnQ:232846:

public void BttnW_click1(GButton source, GEvent event) { //_CODE_:BttnW:342648:
  xbee.write('W');  
  println("BttnW - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BttnW:342648:

public void BttnE_click1(GButton source, GEvent event) { //_CODE_:BttnE:510716:
  xbee.write('E');
  println("BttnE - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BttnE:510716:

public void BttnA_click1(GButton source, GEvent event) { //_CODE_:BttnA:801438:
  xbee.write('A');
  println("BttnA - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BttnA:801438:

public void BttnS_click1(GButton source, GEvent event) { //_CODE_:BttnS:526113:
  xbee.write('S');
  println("BttnS - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BttnS:526113:

public void BttnD_click1(GButton source, GEvent event) { //_CODE_:BttnD:649305:
  xbee.write('D');
  println("BttnD - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BttnD:649305:

public void InputTray_change1(GTextArea source, GEvent event) { //_CODE_:InputTray:544553:
  println("InputTray - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:InputTray:544553:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  BttnQ = new GButton(this, 150, 100, 80, 30);
  BttnQ.setText("Q");
  BttnQ.setTextBold();
  BttnQ.addEventHandler(this, "BttnQ_click1");
  BttnW = new GButton(this, 241, 100, 80, 30);
  BttnW.setText("W");
  BttnW.setTextBold();
  BttnW.addEventHandler(this, "BttnW_click1");
  BttnE = new GButton(this, 330, 100, 80, 30);
  BttnE.setText("E");
  BttnE.setTextBold();
  BttnE.addEventHandler(this, "BttnE_click1");
  BttnA = new GButton(this, 150, 140, 80, 30);
  BttnA.setText("A");
  BttnA.setTextBold();
  BttnA.addEventHandler(this, "BttnA_click1");
  BttnS = new GButton(this, 240, 140, 80, 30);
  BttnS.setText("S");
  BttnS.setTextBold();
  BttnS.addEventHandler(this, "BttnS_click1");
  BttnD = new GButton(this, 330, 140, 80, 30);
  BttnD.setText("D");
  BttnD.setTextBold();
  BttnD.addEventHandler(this, "BttnD_click1");
  LblInputTray = new GLabel(this, 149, 207, 80, 20);
  LblInputTray.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  LblInputTray.setText("Input Tray");
  LblInputTray.setTextBold();
  LblInputTray.setOpaque(false);
  InputTray = new GTextArea(this, 148, 242, 500, 200, G4P.SCROLLBARS_BOTH | G4P.SCROLLBARS_AUTOHIDE);
  InputTray.setOpaque(true);
  InputTray.addEventHandler(this, "InputTray_change1");
}

// Variable declarations 
// autogenerated do not edit
GButton BttnQ; 
GButton BttnW; 
GButton BttnE; 
GButton BttnA; 
GButton BttnS; 
GButton BttnD; 
GLabel LblInputTray; 
GTextArea InputTray; 