/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void Send_Click(GButton source, GEvent event) { //_CODE_:Send:358782:
  println("Send - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Send:358782:

public void SendField_change1(GTextField source, GEvent event) { //_CODE_:SendField:296774:
  println("SendField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:SendField:296774:

public void ReceiveField_change1(GTextField source, GEvent event) { //_CODE_:ReceiveField:854981:
  println("ReceiveField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:ReceiveField:854981:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window1:624408:
  appc.background(230);
} //_CODE_:window1:624408:

public void BtnQ_click1(GButton source, GEvent event) { //_CODE_:BtnQ:402919:
  println("BtnQ - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BtnQ:402919:

public void BtnW_click1(GButton source, GEvent event) { //_CODE_:BtnW:715827:
  println("BtnW - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BtnW:715827:

public void BtnE_click1(GButton source, GEvent event) { //_CODE_:BtnE:955999:
  println("BtnE - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:BtnE:955999:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  Send = new GButton(this, 360, 285, 80, 30);
  Send.setText("Send Message");
  Send.addEventHandler(this, "Send_Click");
  SendField = new GTextField(this, 278, 248, 160, 30, G4P.SCROLLBARS_NONE);
  SendField.setOpaque(true);
  SendField.addEventHandler(this, "SendField_change1");
  ReceiveField = new GTextField(this, 300, 382, 160, 30, G4P.SCROLLBARS_NONE);
  ReceiveField.setOpaque(true);
  ReceiveField.addEventHandler(this, "ReceiveField_change1");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 960, 480, JAVA2D);
  window1.noLoop();
  window1.addDrawHandler(this, "win_draw2");
  BtnQ = new GButton(window1, 133, 73, 80, 30);
  BtnQ.setText("Q");
  BtnQ.setTextBold();
  BtnQ.addEventHandler(this, "BtnQ_click1");
  BtnW = new GButton(window1, 353, 74, 80, 30);
  BtnW.setText("W");
  BtnW.setTextBold();
  BtnW.addEventHandler(this, "BtnW_click1");
  BtnE = new GButton(window1, 594, 79, 80, 30);
  BtnE.setText("E");
  BtnE.setTextBold();
  BtnE.addEventHandler(this, "BtnE_click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GButton Send; 
GTextField SendField; 
GTextField ReceiveField; 
GWindow window1;
GButton BtnQ; 
GButton BtnW; 
GButton BtnE; 